server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/applications/**

            - id: document-service
              uri: lb://document-service
              predicates:
                - Path=/documents/**

            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/admin/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway

  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${JWT_SECRET:finflowsecretkeyforhs256algorithm}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Application Service
        url: /applications/v3/api-docs
      - name: Document Service
        url: /documents/v3/api-docs
      - name: Admin Service
        url: /admin/v3/api-docs
      - name: Notification Service
        url: /notifications/v3/api-docs